require('./../css/bootstrap.css')
// require('./../css/cards.css')
// require('./../css/estilos.css')
require('./../css/maicons.css')
require('./../css/simulador.css')
require('./../css/theme.css')
require('./../css/pagar.css')
