require('./../css/bootstrap.css')
// require('./../css/cards.css')
// require('./../css/estilos.css')
// require('./../css/maicons.css')
// require('./../css/simulaDeuda.css')
require('./../css/theme.css')
require('./../css/simulaDeuda2.css')